name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        test: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 8']
        destination: ['generic/platform=iOS']
        xcode: ['/Applications/Xcode_11.2.1.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v2
    - name: Build App
      env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      run: xcodebuild -project 'ChuckNorrisFacts/ChuckNorrisFacts.xcodeproj' -scheme 'ChuckNorrisFacts' -destination "${{ matrix.destination }}" -configuration Release build CODE_SIGNING_ALLOWED=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
    - name: Run Tests
      env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      run: xcodebuild clean test -project 'ChuckNorrisFacts/ChuckNorrisFacts.xcodeproj' -scheme 'ChuckNorrisFacts' -destination "${{ matrix.test }}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO 
