name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build App
      run: xcodebuild -project 'ChuckNorrisFacts/ChuckNorrisFacts.xcodeproj' -scheme 'ChuckNorrisFacts' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: swift test -v
